---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: merchandise
  labels:
    app: merchandise
spec:
  replicas: 2
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 30%
      maxUnavailable: 30%
  selector:
    matchLabels:
      app: merchandise
  template:
    metadata:
      labels:
        app: merchandise
    spec:
      containers:
        - name: merchandise
          image: quay.io/willtrking/kubecon2018:7
          command:
            - /kubecon2018-linux
            - merchandise
          ports:
          - name: grpc
            containerPort: 10000